
# Generated by Django 3.0.3 on 2020-06-28 10:47



from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.FloatField(default=0)),
                ('voted', models.FloatField(default=0)),
                ('votePer', models.FloatField(default=0)),
            ],
        ),
    ]
