# Generated by Django 3.0.3 on 2020-06-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataBase2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.FloatField(default=0)),
                ('voted', models.FloatField(default=0)),
                ('votePer', models.FloatField(default=0)),
            ],
        ),
    ]
